Repository fga-eps-mds/2018.2-Lino, pull requests merged in 2018-10, with the labels that each got.

#99 Criar pipeline para deploy
  .gitlab-ci.yml
  docker/Messenger.Dockerfile
  rasa/actions/menu.py
  rasa/actions/notifications.py
  rasa/domain.yml
  rasa/notifier.py
  rasa/train-messenger.py
  rasa/train.py
Labels: DevOps, EPS

#106 Adiciona o fluxo de conversa para obtenção do cardápio diário
  .gitlab-ci.yml
  Dockerfile
  rasa/actions/menu.py
  rasa/actions/notifications.py
  rasa/data/intents/documents.md
  rasa/data/intents/email.md
  rasa/data/intents/general.md
  rasa/data/intents/menu.md
  rasa/data/intents/nlu.md
  rasa/data/intents/notifications.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/fb_credentials.yml
  rasa/notifier.py
  rasa/train.py
Labels: Fluxo, MDS

#121 Cria fluxo de conversa no Telegram para obter cardápio diário
  Dockerfile
  docker/Telegram.Dockerfile
  docs/Backlog-do-produto.md
  rasa/actions/menu.py
  rasa/credentials.yml
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/train-telegram.py
  rasa/train.py
Labels: MDS

#129 Estabiliza a master com continuous deploy
  .gitlab-ci.yml
  Dockerfile
  README.md
  docker-compose.yml
  docker/Messenger.Dockerfile
  docker/Telegram.Dockerfile
  docs/Backlog-do-produto.md
  rasa/actions/menu.py
  rasa/actions/notifications.py
  rasa/credentials.yml
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/notification_config.py
  rasa/notifier.py
  rasa/train-messenger.py
  rasa/train-telegram.py
  rasa/train.py
  requirements.txt
Labels: Código, EPS

#139 Refatorar método do Cardápio Diário para o Telegram
  docker-compose.yml
  rasa/actions/notifications/register_notifications.py
  rasa/actions/notifications/start.py
  rasa/data/intents/notifications.md
  rasa/domain.yml
  rasa/ru_notifier.py
Labels: Código, EPS, MDS, Refatoração
