Repository fga-eps-mds/2018.2-Lino, pull requests merged in 2018-09, with the labels that each got.

#39 Documento de Metodologia
  docs/metodologia.md
Labels: Documentação, EPS, TL

#43 Adiciona a abertura da Sprint 2
  docs/sprints/Abertura-Sprint-2.md
Labels: Documentação, EPS

#37 [WIP] Documento de visão
  docs/documento-de-visao.md
Labels: Documentação, MDS

#46 Correção na política de commits
  docs/policies/commits.md
Labels: Documentação

#59 [WIP] Refatoração do Documento de Arquitetura
  docs/documento-de-arquitetura.md
Labels: Arquitetura, Documentação, MDS

#64 Adiciona arquivo do Canvas
  docs/abertura/canvas.md
Labels: Documentação, EPS, PO, Produto

#65 Adiciona primeira versão do Roadmap
  docs/roadmap.md
Labels: Documentação, EPS, PO, Roadmap

#54 Conecta o Rasa ao Telegram
  rasa/Makefile
  rasa/credentials.yml
  rasa/data/nlu.md
  rasa/data/stories.md
  rasa/domain.yml
  rasa/instructions.md
  rasa/nlu_config.yml
Labels: Código, MDS

#66 Adds first version of analytical structure of the project
  docs/eap.md
Labels: Documentação, EPS, Elicitação, PO

#41 Termo de Abertura
  docs/interviews/interviews.md
  docs/termo-de-abertura.md
Labels: Documentação, EPS, PO

#42 [WIP] Backlog do Produto
  docs/Backlog-do-produto.md
Labels: Backlog, Documentação, EPS

#74 Fechamento da Sprint 2
  docs/sprints/Fechamento-Sprint-2.md
Labels: Documentação, EPS, TL

#78 Adiciona a Abertura de Sprint 4
  docs/sprints/Abertura-Sprint-4.md
Labels: Documentação, TL

#56 Busca informações sobre o cardápio do RU
  .gitignore
  crawler/__pycache__/scraper.cpython-36.pyc
  crawler/crawler/__init__.py
  crawler/crawler/__pycache__/__init__.cpython-36.pyc
  crawler/crawler/__pycache__/items.cpython-36.pyc
  crawler/crawler/__pycache__/pipelines.cpython-36.pyc
  crawler/crawler/__pycache__/settings.cpython-36.pyc
  crawler/crawler/items.py
  crawler/crawler/middlewares.py
  crawler/crawler/pipelines.py
  crawler/crawler/settings.py
  crawler/crawler/spiders/RU.py
  crawler/crawler/spiders/__init__.py
  crawler/crawler/spiders/__pycache__/RU.cpython-36.pyc
  crawler/crawler/spiders/__pycache__/__init__.cpython-36.pyc
  crawler/scraper.py
  crawler/scrapy.cfg
  requirements.txt
Labels: Código, MDS

#80 Adiciona WebCrawler e suas funcionalidades derivadas
  .gitignore
  crawler/__pycache__/scraper.cpython-36.pyc
  crawler/crawler/__init__.py
  crawler/crawler/__pycache__/__init__.cpython-36.pyc
  crawler/crawler/__pycache__/items.cpython-36.pyc
  crawler/crawler/__pycache__/pipelines.cpython-36.pyc
  crawler/crawler/__pycache__/settings.cpython-36.pyc
  crawler/crawler/items.py
  crawler/crawler/middlewares.py
  crawler/crawler/pipelines.py
  crawler/crawler/settings.py
  crawler/crawler/spiders/RU.py
  crawler/crawler/spiders/__init__.py
  crawler/crawler/spiders/__pycache__/RU.cpython-36.pyc
  crawler/crawler/spiders/__pycache__/__init__.cpython-36.pyc
  crawler/outputs/FGA0.tsv
  crawler/outputs/FGA1.tsv
  crawler/scraper.py
  crawler/scrapy.cfg
  requirements.txt
Labels: Código, MDS

#84 Conecta o Lino com o Messenger Facebook
  .DS_Store
  .gitignore
  Dockerfile
  docs/.DS_Store
  rasa/Makefile
  rasa/credentials.yml
  rasa/fb_credentials.py
  rasa/train.py
Labels: Código, Estudo, MDS

#82 Conecta o Lino ao Webcrawler
  rasa/actions/__init__.py
  rasa/actions/menu.py
  rasa/data/intents/nlu.md
  rasa/data/stories/stories.md
  rasa/domain.yml
  rasa/nlu_config.yml
Labels: Código, MDS

#93 [Issue_40] Adds Fechamento-Sprint-4.md
  docs/sprints/Fechamento-Sprint-4.md
Labels: Documentação, Metodologia, TL

#101 Folha de Estilo
  crawler/__pycache__/scraper.cpython-36.pyc
  crawler/crawler/__init__.py
  crawler/crawler/__pycache__/__init__.cpython-36.pyc
  crawler/crawler/__pycache__/items.cpython-36.pyc
  crawler/crawler/__pycache__/pipelines.cpython-36.pyc
  crawler/crawler/__pycache__/settings.cpython-36.pyc
  crawler/crawler/items.py
  crawler/crawler/middlewares.py
  crawler/crawler/pipelines.py
  crawler/crawler/settings.py
  crawler/crawler/spiders/RU.py
  crawler/crawler/spiders/__init__.py
  crawler/crawler/spiders/__pycache__/RU.cpython-36.pyc
  crawler/crawler/spiders/__pycache__/__init__.cpython-36.pyc
  crawler/outputs/FGA0.tsv
  crawler/outputs/FGA1.tsv
  crawler/scraper.py
  crawler/scrapy.cfg
  docs/Fluxo_Lino-1.0
  docs/PersonalidadeDoBot.md
  docs/identidade-visual.md
  docs/nfr.md
  docs/policies/style_sheet.md
  docs/sprints/Fechamento-Sprint-3.md
  docs/sprints/Fechamento-Sprint-4.md
Labels: Código, Documentação, EPS, TL

#108 Cria cronjob das notificações
  cron.requirements.txt
  cronjob.Dockerfile
  rasa/actions/notifications.py
  rasa/crontab
  rasa/data/intents/nlu.md
  rasa/data/stories/stories.md
  rasa/domain.yml
  rasa/notifier.py
  rasa/notify.sh
  req.txt
Labels: Código, MDS
