Repository fga-eps-mds/2018.2-Lino, pull requests merged in 2018-11, with the labels that each got.

#152 Refatoração do fluxo de conversa
  README.md
  cron.requirements.txt
  docker-compose.yml
  docker/Cronjob.Dockerfile
  rasa/actions/calendar.py
  rasa/actions/menu/daily_menu.py
  rasa/actions/notifications/register_notification.py
  rasa/actions/notifications/start.py
  rasa/crontab
  rasa/data/intents/documents.md
  rasa/data/intents/email.md
  rasa/data/intents/general.md
  rasa/data/intents/menu.md
  rasa/data/intents/notifications.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/email_notifier.py
  rasa/notification_config.py
  rasa/scripts/email_notifier.py
  rasa/scripts/notify.sh
  rasa/scripts/notify_gmail.sh
  rasa/scripts/notify_week_meal.sh
  rasa/scripts/ru_notifier.py
  rasa/scripts/week_notifier.py
  rasa/train-messenger.py
  rasa/train-telegram.py
  rasa/train.py
Labels: Fluxo, MDS, Refatoração

#162 Cria fluxo de conversa pro cardápio semanal
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  cron.requirements.txt
  docker-compose.yml
  docker/Cronjob.Dockerfile
  docs/policies/pull_request.md
  docs/sprints/Abertura-Sprint-2.md
  docs/sprints/Abertura-Sprint-4.md
  docs/sprints/Abertura-Sprint-5.md
  docs/sprints/Abertura-Sprint-6.md
  docs/sprints/Abertura-Sprint-7.md
  docs/sprints/Abertura-Sprint-8.md
  docs/sprints/Fechamento-Sprint-0.md
  docs/sprints/Fechamento-Sprint-1.md
  docs/sprints/Fechamento-Sprint-2.md
  docs/sprints/Fechamento-Sprint-3.md
  docs/sprints/Fechamento-Sprint-4.md
  docs/sprints/Fechamento-Sprint-5.md
  docs/sprints/Fechamento-Sprint-6.md
  docs/sprints/Fechamento-Sprint-7.md
  docs/sprints/Fechamento-Sprint-8.md
  rasa/actions/calendar.py
  rasa/actions/menu.py
  rasa/actions/menu/daily_menu.py
  rasa/actions/notifications.py
  rasa/actions/notifications/register_notification.py
  rasa/actions/notifications/start.py
  rasa/crontab
  rasa/data/intents/calendar.md
  rasa/data/intents/documents.md
  rasa/data/intents/email.md
  rasa/data/intents/general.md
  rasa/data/intents/menu.md
  rasa/data/intents/notifications.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/nlu_config.yml
  rasa/notification_config.py
  rasa/notifier.py
  rasa/scripts/email_notifier.py
  rasa/scripts/notify.sh
  rasa/scripts/notify_gmail.sh
  rasa/scripts/notify_week_meal.sh
  rasa/scripts/ru_notifier.py
  rasa/scripts/week_notifier.py
  rasa/train-messenger.py
  rasa/train-telegram.py
  rasa/train.py
  requirements.txt
Labels: Código, EPS, MDS

#161 Cria custom action para o calendário acadêmico
  rasa/actions/calendar.py
Labels: Código, Fluxo, MDS

#163 Adiciona variáveis de ambiente pro banco de dados
  docker-compose.yml
  rasa/actions/notifications/register_notification.py
  rasa/actions/notifications/start.py
Labels: Código, bug

#165 Cria script pra carregar variáveis de ambiente
  docker/Cronjob.Dockerfile
  rasa/crontab
  rasa/scripts/env_loader.py
Labels: Código, bug

#176 Altera dockerfile do cronjob
  docker/Cronjob.Dockerfile
  rasa/scripts/entrypoint_cron.sh
Labels: bug

#177 Cria o script de envio do almoço
  docker/Cronjob.Dockerfile
  rasa/crontab
  rasa/scripts/env_loader.py
  rasa/scripts/lunch_notifier.py
  rasa/scripts/notify_lunch.sh
Labels: Código, EPS, MDS

#179 Cria script de envio do Jantar
  docker/Cronjob.Dockerfile
  rasa/crontab
  rasa/scripts/dinner_notifier.py
  rasa/scripts/notify_dinner_meal.sh
Labels: Código, EPS, MDS

#187 Cria botões para auxílio no cadastro de notificações
  docker-compose.yml
  rasa/actions/notifications/buttons_notification.py
  rasa/actions/notifications/register_notification.py
  rasa/actions/notifications/start.py
  rasa/data/intents/general.md
  rasa/data/intents/notifications.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/email_notifier.py
Labels: Código, MDS

#189 Refatora obtenção do cardápio específico e recupera tratamento de erros
  docker-compose.yml
  rasa/actions/menu/daily_breakfast.py
  rasa/actions/menu/daily_dinner.py
  rasa/actions/menu/daily_lunch.py
  rasa/data/intents/menu.md
  rasa/data/intents/notifications.md
Labels: Código, Refatoração, bug

#190 Adiciona features relacionadas a obtenção de cardápios específicos.
  docker-compose.yml
  docker/Cronjob.Dockerfile
  rasa/actions/menu/daily_breakfast.py
  rasa/actions/menu/daily_dinner.py
  rasa/actions/menu/daily_lunch.py
  rasa/actions/menu/daily_menu.py
  rasa/actions/notifications/buttons_notification.py
  rasa/actions/notifications/register_notification.py
  rasa/actions/notifications/start.py
  rasa/crontab
  rasa/data/intents/general.md
  rasa/data/intents/menu.md
  rasa/data/intents/notifications.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/email_notifier.py
  rasa/scripts/breakfast_notifier.py
  rasa/scripts/dinner_notifier.py
  rasa/scripts/entrypoint_cron.sh
  rasa/scripts/env_loader.py
  rasa/scripts/lunch_notifier.py
  rasa/scripts/notify_breakfast_meal.sh
  rasa/scripts/notify_dinner_meal.sh
  rasa/scripts/notify_lunch.sh
Labels: Código, EPS, Fluxo, MDS, PO

#195 Resolve o problema de cache da imagem
  rasa/actions/menu/daily_breakfast.py
  rasa/actions/menu/week_menu.py
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: bug

#210 Refatora botões das notificações no Facebook
  rasa/actions/notifications/buttons_notification.py
  rasa/actions/notifications/register_notification.py
Labels: Banco de Dados, Código, Refatoração

#212 Cria fluxo com tutorial de comprovante de matrícula
  rasa/actions/documents/register_proof.py
  rasa/data/intents/documents.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/images/RegisterProof/step1.png
  rasa/images/RegisterProof/step2.png
  rasa/images/RegisterProof/step3.png
  rasa/images/RegisterProof/step4.png
  rasa/images/RegisterProof/step5.png
Labels: Código, EPS, Fluxo, MDS

#214 Cria fluxo com tutorial de Aluno regular
  rasa/actions/documents/regular_proof.py
  rasa/data/intents/documents.md
  rasa/data/stories/main.md
  rasa/domain.yml
  rasa/images/RegularProof/step1.png
  rasa/images/RegularProof/step2.png
  rasa/images/RegularProof/step3.png
  rasa/images/RegularProof/step4.png
  rasa/images/RegularProof/step5.png
Labels: Código, EPS, Fluxo, MDS

#223 Refatoração do fluxo de conversa dos documentos
  rasa/data/intents/documents.md
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: Fluxo, MDS, Refatoração, bug

#215 [WIP] Cria fluxo para tratar ofensas
  rasa/data/intents/offenses.md
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: Código, EPS, Fluxo, MDS

#216 [WIP] Criação do fluxo do comando /start
  rasa/data/intents/commands.md
  rasa/data/intents/general.md
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: Código, EPS, Fluxo, MDS

#217 [WIP] Cria fluxo para tratamento de elogios
  rasa/data/intents/compliments.md
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: Código, EPS, Fluxo, MDS

#219 [WIP] Cria o fluxo de agradecimento do Lino
  rasa/data/intents/general.md
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: Código, EPS, Fluxo, MDS

#224 Criação do fluxo do comando /help
  rasa/data/intents/general.md
  rasa/data/stories/main.md
  rasa/domain.yml
Labels: Código, EPS, Fluxo, MDS

#230 Conserta o link de images nos fluxos de Tutorial
  rasa/actions/documents/register_proof.py
  rasa/actions/documents/regular_proof.py
  rasa/actions/documents/schedule.py
  rasa/domain.yml
Labels: Código, MDS, bug

#231 Conserta o link de images nos fluxos de Tutorial
  rasa/actions/documents/register_proof.py
  rasa/actions/documents/regular_proof.py
  rasa/actions/documents/schedule.py
  rasa/domain.yml
Labels: Código, MDS, bug

#229 Refatora docs
  docs/Backlog-do-produto.md
Labels: Backlog, Documentação, EPS, PO

#242 Organiza pastas
  cron.requirements.txt
  cronjob/crontab
  cronjob/scripts/breakfast_notifier.py
  cronjob/scripts/dinner_notifier.py
  cronjob/scripts/email_notifier.py
  cronjob/scripts/entrypoint_cron.sh
  cronjob/scripts/env_loader.py
  cronjob/scripts/lunch_notifier.py
  cronjob/scripts/notify.sh
  cronjob/scripts/notify_breakfast_meal.sh
  cronjob/scripts/notify_dinner_meal.sh
  cronjob/scripts/notify_gmail.sh
  cronjob/scripts/notify_lunch.sh
  cronjob/scripts/notify_week_meal.sh
  cronjob/scripts/ru_notifier.py
  cronjob/scripts/week_notifier.py
  docker/Cronjob.Dockerfile
  rasa/email_notifier.py
  req.txt
Labels: Aprimoramento, Refatoração

#251 Cria documento de DevOps/Gitflow
  docs/gitflow.md
Labels: DevOps, Documentação, EPS

#252 Adiciona integração contínua para ambiente de homologação
  .gitlab-ci.yml
Labels: Código, DevOps
